name: CI - Tests & Coverage
on:
  pull_request:
    branches: [ "master", "develop" ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing dependencies
        run: npm ci --legacy-peer-deps

      - name: Linting
        run: npm run lint

  tests:
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests with coverage
        run: npm run test

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Installing dependencies
        run: npm ci --legacy-peer-deps

      - name: Building app
        run: npm run build
